# TODO: This doesn't work in editor, but works with crane. Huh?
[[disallowed-methods]]
path        = "unicode_width::UnicodeWidthStr::width"
reason      = "UnicodeWidthStr::width does not handle emoji or tabs"
replacement = "cab_why::width"
