[formatting]
align_entries         = true
compact_arrays        = false
reorder_inline_tables = true
reorder_keys          = true

[[rule]]
include = [ "**/Cargo.toml" ]
keys    = [ "package" ]

[rule.formatting]
reorder_keys = false
