[workspace]
members  = [ "cab*", "fuzz", "task" ]
resolver = "3"

[workspace.package]
description = "A reproducible contextful-expression language"
edition     = "2024"
license     = "MIT"
publish     = false
repository  = "https://github.com/cull-os/cab"
version     = "0.0.1"

[workspace.dependencies]
log               = "0.4.21"
num               = "0.4.3"
static_assertions = "1.1.0"

[workspace.dependencies.derive_more]
features = [ "full" ]
version  = "2.0.1"

[workspace.dependencies.yansi]
features = [ "detect-env", "detect-tty", "hyperlink" ]
version  = "1.0.1"
