cargo-features = [ "edition2024" ]

[package]
name                  = "cab-report"
description.workspace = true
edition.workspace     = true
license.workspace     = true
publish.workspace     = true
repository.workspace  = true
version.workspace     = true

[dependencies]
const-str          = "0.6.2"
env_logger         = "0.11.6"
log.workspace      = true
scopeguard         = "1.2.0"
smallvec.workspace = true
terminal_size      = "0.4.1"
unicode-width      = "0.2.0"
yansi.workspace    = true
