cargo-features = [ "edition2024" ]

[package]
name                  = "cab-report"
description.workspace = true
edition.workspace     = true
license.workspace     = true
publish.workspace     = true
repository.workspace  = true
version.workspace     = true

[dependencies]
env_logger      = "0.11.6"
log.workspace   = true
unicode-width   = "0.2.0"
yansi.workspace = true
