[package]
name    = "cab-syntax"
version = "0.0.1"
edition = "2021"

[dependencies]
derive_more = "0.99.18"
enumset     = "1.1.3"
log         = "0.4.21"
num_enum    = "0.7.2"
peekmore    = "1.3.0"
rowan       = "0.15.15"

[dependencies.rug]
version          = "1.24.1"
default-features = false
features         = [ "integer", "float", "std" ]

[dependencies.yansi]
version  = "1.0.1"
features = [ "detect-env", "detect-tty", "hyperlink" ]
