[package]
name    = "cab-syntax"
version = "0.0.1"
edition = "2021"

[dependencies]
colored     = "2.1.0"
derive_more = "0.99.18"
enumset     = "1.1.3"
log         = "0.4.21"
multipeek   = "0.1.2"
num_enum    = "0.7.2"
rowan       = "0.15.15"
