[package]
name                 = "cab-syntax"
edition.workspace    = true
license.workspace    = true
publish.workspace    = true
repository.workspace = true
version.workspace    = true

[dependencies]
enumset           = "1.1.3"
log               = "0.4.21"
num               = "0.4.3"
num_enum          = "0.7.2"
peekmore          = "1.3.0"
rowan             = "0.16.1"
static_assertions = "1.1.0"

[dependencies.derive_more]
features = [ "full" ]
version  = "1.0.0"

[dependencies.phf]
features = [ "macros" ]
version  = "0.11.3"

[dependencies.yansi]
features = [ "detect-env", "detect-tty", "hyperlink" ]
version  = "1.0.1"
